spring.application.name=device-management-service

### Database ###
spring.datasource.url=jdbc:postgresql://${POSTGRES_ADDR}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}